version: 0.0
os: linux

files:
  - source: standalone
    destination: /var/www/sunset-vista-co/standalone

permissions:
  - object: /var/www/sunset-vista-co
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
