version: 0.2

env:
  variables:
    APP_NAME: sunset-vista-co
    ARTIFACT_BUCKET: sunset-vista-website-codebuild
    ARTIFACT_PREFIX: releases

phases:
  install:
    commands:
      - echo "[install] Install Node 24 with nvm"
      - export NVM_DIR=/root/.nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - . "$NVM_DIR/nvm.sh"
      - nvm install 24
      - nvm use 24
      - node -v
      - npm -v
      - corepack enable || true
      - echo "[install] npm ci"
      - npm ci
  build:
    commands:
      - . "$NVM_DIR/nvm.sh" && nvm use 24
      - echo "[build] Next build - standalone output"
      - npm run build
      - echo "[build] Prepare deployment bundle"
      - mkdir -p deploy
      - cp -R .next/standalone deploy/
      - cp -R .next/static deploy/standalone/.next/static
      - if [ -d public ]; then cp -R public deploy/standalone/public; fi
      - cp package.json deploy/standalone/package.json
      - cp appspec.yml deploy/appspec.yml
      - mkdir -p deploy/scripts && cp -R scripts/* deploy/scripts/
      - chmod +x deploy/scripts/*.sh
  post_build:
    commands:
      - . "$NVM_DIR/nvm.sh" && nvm use 24
      - echo "[post_build] Zip and upload artifact, then trigger CodeDeploy"
      - ARTIFACT_NAME=${APP_NAME}-$(date +%Y%m%d%H%M%S).zip
      - cd deploy && zip -r ../$ARTIFACT_NAME . && cd ..
      - aws s3 cp $ARTIFACT_NAME s3://$ARTIFACT_BUCKET/$ARTIFACT_PREFIX/$ARTIFACT_NAME
      - aws deploy register-application-revision --application-name $APP_NAME --s3-location bucket=$ARTIFACT_BUCKET,bundleType=zip,key=$ARTIFACT_PREFIX/$ARTIFACT_NAME
      - aws deploy create-deployment --application-name $APP_NAME --deployment-group-name ${APP_NAME}-prod --s3-location bucket=$ARTIFACT_BUCKET,bundleType=zip,key=$ARTIFACT_PREFIX/$ARTIFACT_NAME

artifacts:
  files:
    - '**/*'
  discard-paths: yes
