import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Taviraj } from 'next/font/google'
import { Rubik } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const taviraj = Taviraj({
  subsets: ['latin'],
  display: 'swap',
  //@ts-ignore
  weight: "400",
  variable: '--font-taviraj'
})

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + taviraj.variable + ' ' + rubik.variable}>{children}</body>
    </html>
  );
}
